<script>
  import SvelteMarkdown from 'svelte-markdown';
  const source = `

We believe that all work takes place within nested levels of complexity. We believe that many people gravitate towards particular levels of complexity that maximize their enjoyment of the experience. This comfort and familiarity can also lead to effectiveness, and vice versa.

We define the Complexiy Levels that we work within as follows:

**Intra-Organizational Complexity**

- **Task** - Delivering a single, discrete task at a time, where understanding the context of details of its associated project is of limited value.
- **Project (a set of Tasks)** - Creating and curating a group of tasks in order to accomplish a stated goal.
- **Program (a set of Projects)** - Owning a high-level objective, dividing that objective into projects that work together towards its completion.
- **Enterprise (a set of Programs)** - Setting high-level objectives, assigning the objectives to programs designed to mutually reinforce success.

**Extra-Orgnizational Complexity**
- **Industry (a set of Enterprises)** - Aggregating trends and insights generated by numerous related Enterprises to understand the competitive meta-game these enterprises play in, and observe how changes in strategy or resource allocations create ripple effects. 
- **Economy (a set of Industries)** - Making observations and connections across an organized set of industries, often defined by imaginary lines drawn across geography, defining them as a Province, Region or Nation.
- **Planet (a set of Economies)** - Discovering problems and solutions that have global levels of impact across a Planet.
- **Universe (a set of Planets)** - Defining laws and truths that govern reality across a set of planetary environments within a defined universe.

It may help to visualize the levels as nested. Here's a visualization of Task through Enterprise: 
[![Task Through Enterprise Levels](/task-through-enterprise.png)](/task-through-enterprise.png)

To visualize all of the levels of nesting would require an incredibly complex diagram. But that's the point; individuals rarely think about _all_ of the levels simultaneously. Most individuals focus on their level, and perhaps the two levels adacent to theirs. 

To give a concrete examples, within an actual enterprise a visibility diagram for a project manager might look more like this:
[![Project Manager Level View](/pm-level-view.png)](pm-level-view.png)

A project-level worker would be aware of the tasks occuring within their project, though they may be unable to actually execute on the majority of them. They would also have awareness and understanding of the Projects _around_ them, within their Program. Their awareness of how the various Projects interact to serve the needs of the next level up, the Program, would be less pertinent. They would have only a vague awareness of the mechanics of how various Programs combine and interact as an Enterprise.

[![Levels](/level-scale.png)](/level-scale.png)

Another way to think of the differences between the levels is in terms of **Concreteness versus Abstraction**. Task-level work tends to be highly **Concrete**, whereas Planet and Universe-level work is extraordinarily **Abstract**. Consider how the term "[galaxy brain](https://knowyourmeme.com/memes/galaxy-brain)" is used to describe particularly obtuse and world-changing thoughts.



# Q&A

## Can I learn to operate at a different level?

You may be rebelling against this idea due to an apparent conflict with [Dweck's concept of a growth mindset](https://en.wikipedia.org/wiki/Mindset#Fixed_and_growth_mindset). The levels are not about growth, more about personality: what kind of work do we like doing?  Growth can always occur in the ability to execute within our preferred level.

In many cases, we are still _able_ to work at the levels outside of our preferred level or levels, though we may feel less effective and find the work less joyful. We also may struggle by applying strategies and tactics that worked at our familiar level to a new level. We may not even recognize we’ve switched!

## How do you use this thinking in real life?

When we adopt a problem, we think through the level of organizational complexity required to tackle it. From there, we like to think through prospective team builds for executing within this context.

Getting to know our partners' sweet spots has proven to be useful in building balanced, resilient, effective teams.

## How can I help?

Thanks so much for asking. We would love feedback, comments and questions, including but not limited to:

1. Better names for the categories
2. Discovery of errors or incongruity
3. "Theory Breaking" examples and ideas for improvement
4. Personal anecdotes around using similar or different approaches to understanding how people relate to complexity while producing valuable results

`;
</script>

<svelte:head>
  <title>Role Complexity | SocioTechnica</title>
</svelte:head>

<h1 class="font-serif text-4xl mb-4">Role Complexity</h1>

<div class="italic mb-4 text-sm text-gray-600">Updated November 2022</div>

<article class="prose">
  <SvelteMarkdown {source} />
</article>
